version: '3'
services:
 backend:
  build: ./backend
  command: python manage.py runserver 0.0.0.0:8001
  volumes:
   - ./backend:/code
  ports:
   - "8001:8001"
  depends_on:
   - postgres
 postgres:
  image: postgres:13.4-alpine
  ports:
   - "5432"
  volumes:
   - postgres-data:/var/lib/postgresql/data
  environment:
   TZ: 'Europe/Warsaw'
   PGTZ: 'Europe/Warsaw'
   POSTGRES_DB: homebudget
   POSTGRES_USER: hbadmin
   POSTGRES_PASSWORD: GCxJV8Z3{n!fRq)3
 frontend:
  build: ./frontend
  ports:
   - "81:3000"
  volumes:
   - ./frontend:/code
   - /code/node_modules/
volumes:
  postgres-data:
  backend:
  frontend:

