version: '3'
services:
 backend:
  build: ./backend
  command: python manage.py runserver 0.0.0.0:8001
  volumes:
   - ./backend:/code
  ports:
   - "8001:8001"
  env_file:
   - '.env'
  depends_on:
   - postgres
 postgres:
  image: postgres:13.4-alpine
  ports:
   - "$DB_PORT"
  volumes:
   - postgres-data:/var/lib/postgresql/data
  environment:
   TZ: 'Europe/Warsaw'
   PGTZ: 'Europe/Warsaw'
   POSTGRES_DB: $DB_NAME
   POSTGRES_USER: $DB_USER
   POSTGRES_PASSWORD: $DB_PASSWORD
 frontend:
  build: ./frontend  
  ports:
   - "81:3000"
  environment:
   - REACT_APP_API_PROTOCOL
   - REACT_APP_API_IP
   - REACT_APP_API_PORT
  volumes:
   - ./frontend:/code
   - /code/node_modules/
volumes:
  postgres-data:
  backend:
  frontend:

